name: FTP Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      deployment_mode:
        description: 'Choose deployment mode'
        required: true
        default: 'dry-run'
        type: choice
        options:
          - 'dry-run'
          - 'live'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore File Timestamps
        run: |
          git ls-files -z | while IFS= read -r -d '' file; do
            
            # Get the ISO 8601 timestamp of the last commit for this file
            timestamp=$(git log -1 --format="%cI" -- "$file")
            
            # Apply the timestamp to the file modification time
            touch -d "$timestamp" "$file"

          done

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Sync Files via FTP
        env:
          FTP_SERVER: ${{ vars.FTP_SERVER }}
          FTP_USERNAME: ${{ vars.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          #DRY_RUN_FLAG: >-
          #  ${{ 
          #    github.event_name == 'pull_request' || 
          #    (github.event_name == 'workflow_dispatch' && github.event.inputs.deployment_mode == 'dry-run') 
          #    && '--dry-run' || '' 
          #  }}
          DRY_RUN_FLAG: '--dry-run'
        run: |
          lftp -e "
            set ftp:ssl-allow false;
            open -p 21 -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; 
            mirror ./ ./ \
              --exclude=.github/ \
              --exclude=.git/ \
              --reverse \
              --only-newer \
              --delete \
              --verbose \
              $DRY_RUN_FLAG;
            quit
          "
